---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "RomM CIFS"
    my_file: "install_romm_cifs"
    system_key: "romm"
    module_name: "romm_cifs"

    top_level_paths:
      - { name: "roms",   enabled: yes,  generic: "roms",   systems: no }
    #  - { name: "saves",  enabled: yes,  generic: "saves",  systems: yes }
      # - { name: "bios",   enabled: yes,  generic: "bios",   systems: yes }

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.import_role:
        name: retronas.role.romdir

    - ansible.builtin.import_role:
        name: retronas.role.extradirs

    - ansible.builtin.import_role:
        name: retronas.role.samba

    - ansible.builtin.import_role:
        name: retronas.role.samba.system

    - ansible.builtin.import_role:
        name: retronas.role.system-config
